const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const crypto=require("node:crypto");
const fx=require("./fixtures/package6-behavior");const handlerPath=path.resolve(__dirname,"../api/script-v2.js");const captures=[];
function model(stage,lang="ru"){return stage==="scene_ideas"?fx.ideas(lang):stage==="selection"?fx.selection(lang):stage==="development"?fx.development(lang):stage==="refinement"?{message:lang==="en"?"Usable refinement message.":"Рабочий refinement ответ.",suggestions:[],confirmation_label:null}:stage==="alignment"?fx.alignment(lang):{blocks:{video_overview:"Usable overview"}};}
async function capture(stage,{language="ru",bp=fx.blueprint(),user_input,conversation}={}){const oldKey=process.env.OPENAI_API_KEY,oldFetch=global.fetch;process.env.OPENAI_API_KEY="mock-only";let body;global.fetch=async(_u,req)=>{body=JSON.parse(req.body);return{ok:true,async json(){return{output_text:JSON.stringify(model(stage,language))}}};};delete require.cache[handlerPath];const handler=require(handlerPath);const request={stage,language,blueprint:bp,user_input:user_input??(stage==="selection"?{seed_scene:"Scene"}:stage==="refinement"?"mixed English и русский 1":{raw_text:"mixed English и русский 1"}),ui_context:{scene_action:"reveal"},meta:stage==="build"?{result_schema:fx.buildSchema()}:stage==="refinement"?{refinement_operation:"chat",refinement_conversation:conversation??[{role:"user",content:"Earlier transient refinement item"}]}:{}};let payload;const res={setHeader(){},status(){return this;},json(v){payload=v;},end(){}};try{await handler({method:"POST",body:request},res);const item={stage,language,request_input:body.input,response_status:payload.status};captures.push(item);return item;}finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=oldKey;}}
function text(c){return c.request_input.map(x=>x.content.map(y=>y.text).join("\n")).join("\n");}
test("role directives materially differ for four roles",async()=>{const vals=[];for(const role of ["creative_director","commercial_strategist","cinematographer","film_director"]){const c=await capture("scene_ideas",{bp:fx.blueprint({meta:{scriptwriter_role:role}})});vals.push(text(c));}assert.equal(new Set(vals).size,4);for(const [v,term] of [[vals[0],"concept"],[vals[1],"audience"],[vals[2],"camera"],[vals[3],"staging"]])assert.match(v,new RegExp(term,"i"));});
test("type directives materially differ for five types",async()=>{const vals=[];for(const type of ["video","promo","interactive","video_prompt","image_prompt"]){vals.push(text(await capture("development",{bp:fx.blueprint({meta:{video_type:type}})})));}assert.equal(new Set(vals).size,5);});
test("goal emotion action and canonical advanced intent are present",async()=>{const t=text(await capture("scene_ideas"));assert.match(t,/promotion_ad|conversion/i);assert.match(t,/technological/i);assert.match(t,/reveal/i);assert.match(t,/camera_details/i);});
test("refinement prompt ignores retired V2 anchor state and carries transient conversation",async()=>{const bp=fx.blueprint({system_state:{refinement_state:{active_anchor:"visual_tone",open_anchor:true,pending_options:true,options_context:[{id:"o1",label:"x"}],open_question:true,question_context:{id:"q1"},last_user_intent:"wants_more_options"}}});const t=text(await capture("refinement",{bp,conversation:[{role:"user",content:"Earlier transient refinement item"}]}));assert.doesNotMatch(t,/visual_tone|pending_options|wants_more_options|question_context|options_context/);assert.match(t,/Earlier transient refinement item/);});
test("alignment prompt receives role and type context without fixed opening",async()=>{const t=text(await capture("alignment",{bp:fx.blueprint({meta:{scriptwriter_role:"cinematographer",video_type:"image_prompt"}})}));assert.match(t,/cinematographer|camera|composition/i);assert.match(t,/image_prompt|single-frame/i);assert.doesNotMatch(t,/must start|должен начинаться/i);});
test("normal prompts deny route and Build authority",async()=>{for(const stage of ["scene_ideas","selection","development","refinement","alignment"]){const t=text(await capture(stage));assert.match(t,/route|маршрут|readiness|готовност|Build/i);assert.doesNotMatch(t,/you may decide route|ты решаешь маршрут/i);}});
test("RU EN are direct and mixed input does not change trusted language",async()=>{const ru=text(await capture("refinement",{language:"ru",user_input:"English phrase внутри"}));const en=text(await capture("refinement",{language:"en",bp:fx.blueprint({meta:{language:"en"}}),user_input:"русская фраза inside"}));assert.match(ru,/Отвечай только на русском языке/);assert.match(en,/Respond only in English/);});
test("Build prompt capture remains available for baseline comparison",async()=>{const c=await capture("build");assert.equal(c.response_status,"ok");assert.match(text(c),/explicit build surface/);});
test.after(()=>{if(process.env.PACKAGE6_PROMPT_CAPTURE_PATH){const out={generated_at:new Date().toISOString(),captures,build_prompt_sha256:crypto.createHash("sha256").update(JSON.stringify(captures.find(x=>x.stage==="build").request_input)).digest("hex")};fs.writeFileSync(process.env.PACKAGE6_PROMPT_CAPTURE_PATH,JSON.stringify(out,null,2));}});
