const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");
const fx=require("./fixtures/package6-behavior");const handlerPath=path.resolve(__dirname,"../api/script-v2.js");
async function invoke(stage,model,{language="ru",blueprint=fx.blueprint(),user_input,fetchFailText}={}){
 const oldKey=process.env.OPENAI_API_KEY,oldFetch=global.fetch;process.env.OPENAI_API_KEY="mock-only";let requestBody=null;
 global.fetch=async(_u,req)=>{requestBody=JSON.parse(req.body);if(fetchFailText)return{ok:false,async text(){return fetchFailText;}};return{ok:true,async json(){return{output_text:JSON.stringify(model)}}};};
 delete require.cache[handlerPath];const handler=require(handlerPath);let payload,statusCode;const req={method:"POST",body:{stage,language,blueprint,user_input:user_input??defaultInput(stage),ui_context:{scene_action:"reveal"},meta:stage==="build"?{result_schema:fx.buildSchema()}:stage==="refinement"?{refinement_operation:"chat",refinement_conversation:[]}:{}}};const res={setHeader(){},status(c){statusCode=c;return this;},json(v){payload=v;return v;},end(){}};
 try{await handler(req,res);return{payload,statusCode,requestBody};}finally{global.fetch=oldFetch;if(oldKey===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=oldKey;}
}
function defaultInput(stage){if(stage==="selection")return{seed_scene:"Выбранная сцена."};if(stage==="refinement")return"усиль конфликт";return{raw_text:"контекст"};}
function expectControlled(r,stage,code){assert.equal(r.statusCode,200);assert.equal(r.payload.stage,stage);assert.equal(r.payload.status,"error");assert.equal(r.payload.output,null);assert.equal(r.payload.blueprint_patch,null);assert.equal(r.payload.error.code,code);assert.deepEqual(Object.keys(r.payload).sort(),["blueprint_patch","error","meta","output","stage","status"]);}
for(const lang of ["ru","en"]){
 test(`scene ideas valid ${lang}`,async()=>{const r=await invoke("scene_ideas",fx.ideas(lang),{language:lang});assert.equal(r.payload.status,"ok");assert.equal(r.payload.output.ideas.length,3);assert.equal(r.payload.blueprint_patch,null);});
 test(`selection valid ${lang} without automatic question`,async()=>{const r=await invoke("selection",fx.selection(lang),{language:lang});assert.equal(r.payload.status,"ok");assert.deepEqual(r.payload.output.questions,[]);});
 test(`development valid ${lang} with zero questions`,async()=>{const r=await invoke("development",fx.development(lang),{language:lang});assert.equal(r.payload.status,"ok");assert.deepEqual(r.payload.output.questions,[]);assert.ok(r.payload.blueprint_patch["narrative.scene_development"]);});
 test(`refinement valid ${lang}`,async()=>{const bp=fx.blueprint({meta:{language:lang}});const m={message:lang==="en"?"Usable refinement message.":"Рабочий refinement ответ.",suggestions:[]};const r=await invoke("refinement",m,{language:lang,blueprint:bp});assert.equal(r.payload.status,"ok");});
 test(`alignment valid ${lang}`,async()=>{const r=await invoke("alignment",fx.alignment(lang),{language:lang});assert.equal(r.payload.status,"ok");assert.equal(r.payload.output.questions.length,0);});
}
test("scene ideas rejects wrappers",async()=>expectControlled(await invoke("scene_ideas",{output:{ideas:fx.ideas().ideas}}),"scene_ideas","SCENE_IDEAS_RESPONSE_INVALID"));
test("scene ideas rejects duplicate content",async()=>{const m=fx.ideas();m.ideas[1].seed_scene=m.ideas[0].seed_scene;expectControlled(await invoke("scene_ideas",m),"scene_ideas","SCENE_IDEAS_RESPONSE_INVALID");});
test("scene ideas rejects extra idea key",async()=>{const m=fx.ideas();m.ideas[0].route="alignment";expectControlled(await invoke("scene_ideas",m),"scene_ideas","SCENE_IDEAS_RESPONSE_INVALID");});
test("selection rejects two questions",async()=>expectControlled(await invoke("selection",fx.selection("ru",["Один?","Два?"])),"selection","SELECTION_RESPONSE_INVALID"));
test("selection rejects extra top-level key",async()=>expectControlled(await invoke("selection",{...fx.selection(),next_stage:"development"}),"selection","SELECTION_RESPONSE_INVALID"));
test("selection rejects forbidden patch",async()=>expectControlled(await invoke("selection",{...fx.selection(),patch:{narrative:{scene_setup:"x"}}}),"selection","SELECTION_RESPONSE_INVALID"));
test("development rejects two questions",async()=>expectControlled(await invoke("development",fx.development("ru",["Один?","Два?"])),"development","DEVELOPMENT_RESPONSE_INVALID"));
test("development rejects empty ok patch",async()=>expectControlled(await invoke("development",{...fx.development(),patch:{}}),"development","DEVELOPMENT_RESPONSE_INVALID"));
test("development rejects protected seed patch",async()=>expectControlled(await invoke("development",{...fx.development(),patch:{scene_core:{seed_scene:"new"}}}),"development","DEVELOPMENT_RESPONSE_INVALID"));
test("development rejects question handoff",async()=>expectControlled(await invoke("development",{...fx.development(),message:"Герой запускает устройство. Продолжим?"}),"development","DEVELOPMENT_RESPONSE_INVALID"));
test("refinement empty message is controlled error, not semantic replacement",async()=>expectControlled(await invoke("refinement",{message:""}),"refinement","REFINEMENT_RESPONSE_FATAL"));
test("alignment rejects two sentences",async()=>expectControlled(await invoke("alignment",{message:"Первая. Вторая.",questions:[]}),"alignment","ALIGNMENT_RESPONSE_INVALID"));
test("alignment rejects direct canonical mutation promise",async()=>expectControlled(await invoke("alignment",{message:"Сцену сохраняем. Результат будет применимым. Я напрямую обновлю canonical result после сборки.",questions:[]}),"alignment","ALIGNMENT_RESPONSE_INVALID"));
test("all normal errors hide raw provider output",async()=>{for(const [stage,code] of [["scene_ideas","SCENE_IDEAS_RESPONSE_INVALID"],["selection","SELECTION_RESPONSE_INVALID"],["development","DEVELOPMENT_RESPONSE_INVALID"],["refinement","REFINEMENT_RESPONSE_FATAL"],["alignment","ALIGNMENT_RESPONSE_INVALID"]]){const r=await invoke(stage,{}, {fetchFailText:"SECRET prompt stack /internal/path"});expectControlled(r,stage,code);assert.doesNotMatch(JSON.stringify(r.payload),/SECRET|internal\/path|stack|prompt/i);}});
test("alignment accepts approved minimum of three sentences",async()=>{const r=await invoke("alignment",{message:"Сцену сохраняем как основу. Главный акцент остаётся на выборе героя. Результат будет применимой структурой ролика.",questions:[]});assert.equal(r.payload.status,"ok");});
test("Build rejects forbidden route key recursively",async()=>{const r=await invoke("build",{blocks:{video_overview:{text:"Usable overview",route:"alignment"}}});assert.notEqual(r.payload.status,"ok");assert.equal(r.payload.output?.blocks?.video_overview,undefined);});
